baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "bat"
[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "topic"
    weight = 100
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
